services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - /frontend/node_modules
      - ./frontend:/frontend

  products-microservice:
    build: ./backend/products-microservice
    restart: always
    ports:
      - "8090:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./backend/products-microservice:/products-microservice
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 3s
      retries: 10
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: mypassword
      DB_NAME: shop-database
      JWT_SECRET: 8fhj3k4j5h2k3j4h5k6j7h8k9j2h3j4k5h6j7h8k9j0k1j2h3g4f5d6s7a8s9d0f
      DB_CONN: "user=postgres password=mypassword dbname=shop-database host=postgres sslmode=disable"
      GOOSE_MIGRATION_DIR: "./migrations"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: myredispassword

  orders-microservice:
    build: ./backend/orders-microservice
    restart: always
    ports:
      - "8091:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./backend/orders-microservice:/orders-microservice
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: mypassword
      DB_NAME: shop-database
      JWT_SECRET: 8fhj3k4j5h2k3j4h5k6j7h8k9j2h3j4k5h6j7h8k9j0k1j2h3g4f5d6s7a8s9d0f
      DB_CONN: "user=postgres password=mypassword dbname=shop-database host=postgres sslmode=disable"
      GOOSE_MIGRATION_DIR: "./migrations"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: myredispassword

  migration-service:
    build: ./backend/migration-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_CONN: "user=postgres password=mypassword dbname=shop-database host=postgres sslmode=disable"

  admin-microservice:
    build: ./backend/admin-microservice
    restart: always
    ports:
      - "8092:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./backend/admin-microservice:/admin-microservice
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 3s
      retries: 10
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: mypassword
      DB_NAME: shop-database
      JWT_SECRET: 8fhj3k4j5h2k3j4h5k6j7h8k9j2h3j4k5h6j7h8k9j0k1j2h3g4f5d6s7a8s9d0f
      DB_CONN: "user=postgres password=mypassword dbname=shop-database host=postgres sslmode=disable"
      GOOSE_MIGRATION_DIR: "./migrations"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: myredispassword

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    command: redis-server --requirepass myredispassword

  postgres:
    image: postgres:15-alpine
    container_name: pg_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: shop-database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "6080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    depends_on:
      - postgres
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - ./pgadmin/pgpass:/pgpass
    user: "root"
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    restart: always
    depends_on:
      zookeeper:
        condition: service_started
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:29092 --list || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  postgres_data:
